name: PathDSP_env
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.4
  - cryptography=41.0.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=1.2.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - fontconfig=2.14.1
  - freetype=2.10.4
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=2.0.1
  - grpc-cpp=1.48.2
  - gseapy=1.0.5
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jbig=2.1
  - jedi=0.19.0
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.3.0
  - jupyter_core=4.12.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcurl=8.1.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.1.2
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - polars=0.18.15
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycairo=1.24.0
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyzmq=25.1.0
  - rdkit=2022.03.2
  - re2=2022.04.01
  - readline=8.2
  - reportlab=3.6.12
  - requests=2.31.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlalchemy=1.4.49
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - astropy==5.3.2
      - contourpy==1.1.0
      - fonttools==4.42.0
      - joblib==1.3.2
      - matplotlib==3.7.2
      - patsy==0.5.3
      - protobuf==3.19.0
      - pyerfa==2.0.0.3
      - pyparsing==3.0.9
      - pyyaml==6.0.1
      - scikit-learn==1.3.0
      - statsmodels==0.14.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
